### ISSUE TITLE
Make branch changes testable in development mode

### ISSUE THREAD

**Issue by colincasey** [heroku/languages-github-actions#106]
In development mode (e.g.; using `@main`) will install the `actions` binary [from this repository's `main` branch](https://github.com/heroku/languages-github-actions/blob/main/.github/actions/install-languages-cli/action.yml#L25).  We may want to extend this to allow for a git-ref to be supplied so that changes can be tested from a feature branch before merging to `main`.

GUS-W-13955891.

**Comment by edmorley** [comment]
I think we should be able to use `github.job_workflow_sha` for this case right? Since we won't be using it in a `use:` definition (where dynamic values aren't permitted), but instead can use it inside a `with:` to pass the SHA to the "install languages CLI" action?

**Comment by colincasey** [comment]
from the documentation you would think that `github.job_workflow_sha` is the thing to use but according to https://github.com/actions/runner/issues/2417 it is never set. i observed the same behavior when attempting to determine the ref of the shared workflow. 

until the issues with `github.job_workflow_sha` are fixed, i think the only option would be to expose it as an optional input that defaults to `main`.

**Comment by edmorley** [comment]
Ah right - that was the second issue you mentioned about it being null.

I've opened a GitHub support ticket to try and nudge things along with getting that acknowledged as a bug:
https://support.github.com/ticket/personal/0/2287074
