### ISSUE TITLE
Use relative paths to refer to actions in this repo

### ISSUE THREAD

**Issue by edmorley** [heroku/languages-github-actions#37]
(From code review)

              In a few places, the re-usable workflows in this repository refer to other workflows that are also in this repository.

Currently this is done by specifying the full repo path and branch, however, it seems there is a local path syntax which avoids that repetition? (And potentially avoids GitHub Actions from having to clone the repo/files multiple times?)

https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

eg:

```yaml
      uses: ./.github/actions/buildpack-artifact-prefix
```

_Originally posted by @edmorley in https://github.com/heroku/languages-github-actions/pull/20#discussion_r1238497436_

**Comment by colincasey** [comment]
i did read those docs on the reusable workflows but didn't find equivalent documentation for reusable actions.  let me confirm that those work in the same way.

**Comment by colincasey** [comment]
@edmorley this doesn't appear to work the same for actions within a shared workflow.  when using the local path syntax it attempts to load the action relative to the executing repository instead of the shared workflow repository.

**Comment by edmorley** [comment]
Ah thank you for checking :-)
