### ISSUE TITLE
`setup-tools` is unused in the package buildpack workflow

### ISSUE THREAD

**Issue by edmorley** [heroku/languages-github-actions#51]
The `_buildpacks-release-package.yml` workflow currently installs yj/crane/... here:
https://github.com/heroku/languages-github-actions/blob/b17eaa3156924ccb4fc6d38d2edd8ad7ac5617a5/.github/workflows/_buildpacks-release-package.yml#L50-L51

However, the package step doesn't use any of those tools. (Nothing in this repo uses yj, and only the update-builder and publish to CNB registry workflows use crane.)

**Comment by colincasey** [comment]
ah yes, those tools were previously used to extract metadata in this workflow and are no longer needed.  will drop this step
