### ISSUE TITLE
Publish a new version of the actions binary

### ISSUE THREAD

**Issue by edmorley** [heroku/languages-github-actions#54]
Since there have been changes to the Rust parts of this repo (which as far as I can tell need explicit releases, unlike the workflow parts which are pulled from `main`) since the last release:
https://github.com/heroku/languages-github-actions/compare/v0.0.1...main#files_bucket

**Comment by colincasey** [comment]
@edmorley the new version is being published but overwriting the current release.  the tag does not get updated though.  this is already captured in #13.  closing as a duplicate.
